### ISSUE TITLE
ESP32C3 SPI mode can't read the IDCODE

### ISSUE THREAD

**Issue by sczh01** [windowsair/wireless-esp8266-dap#44] opened 2022-10-31 15:32 UTC
CLK<10Mhz, the Last version can work normally by elaphureLink.
![image](https://user-images.githubusercontent.com/287193/199046785-faba74f4-806b-4024-93b7-ceb165d87ad2.png)

CLK=10Mhz, can't read the IDCODE in the configration page.
![image](https://user-images.githubusercontent.com/287193/199046468-d3193307-cfec-4105-afdf-7d959babc707.png)
I check the SPI clock is 40Mhz as expected, I doubt the speed should be to fast, then decrease into 10Mhz. Still can't read the ID.

**Comment by windowsair** [comment] 2022-10-31 15:38
If you select the 10MHz clock in the configration page, then you are actually using a 40MHz SPI clock.

The ESP32C3 should be available and I have tested it. So in this situation I would suggest to check your line connection.

**Comment by windowsair** [comment] 2022-11-03 15:02
I tested again the ESP32C3 related functions and was unable to reproduce the error you mentioned. I will close this issue, but feel free to reopen it at any time.

**Closed by windowsair** 2022-11-03 15:02 UTC
